#!/bin/bash

fns="fig_deepleabra_pred_vis_motion fig_deepleabra_wwi_model fig_deepleabra_wwi_env fig_xcal_bcm_err_learn fig_xcal_dwt_fun_urakubo_fit_full fig_cortical_cons_ff_fb fig_markov_et_al_super_deep  fig_deepleabra_cons fig_markov_et_al_cort_hier fig_deepleabra_cons_pulv fig_deepleabra_wwi_lip_pretrain fig_deepleabra_wwi_train_lcurve fig_deepleabra_wwi_train_lcurve_v23mt fig_deepleabra_wwi_actrf fig_deepleabra_wwi_v2v3only_v1p2 fig_deepleabra_wwi_v3only_decode fig_deepleabra_wwi_noteo_v1p fig_deepleabra_wwi_noteo_mtdecode fig_deepleabra_wwi_no_lip_pre fig_deepleabra_wwi_teo_epc1 fig_deepleabra_wwi_v23pre_decode fig_deepleabra_wwi_nov1p_to_it fig_deepleabra_wwi_it_ctxt fig_deepleabra_wwi_moment_hebb fig_duhamel_colby_goldberg_fig2_remapping fig_deepleabra_wwi_pred_remap_untraj fig_deepleabra_wwi_pred_remap_net fig_super_lamme_01_fig4 fig_lee_mumford03_fig4 fig_deepleabra_wwi_top_down_untraj fig_summerfield_et_al_08_fig1c fig_deepleabra_wwi_tick_act_churn_bar fig_deepleabra_wwi_tick_act_churn_v24 fig_reynolds_heeger_09_fig1 fig_deepleabra_attn_compute fig_reynolds_heeger_09_fig2 fig_attn_deep_reynolds_heeger_09_small_big_attn fig_srn_ti_compute"

for fn in $fns; do
    echo $fn
    cp "figs/$fn.png" arxiv/
done

